functional:
  - Еcть возможность играть как зарегистрированным пользователям, так и не зарегистрированным
  - Есть возможность менять язык программирования во время игры
  - Есть возможность игры с любым пользователем, с ботом и с другом (по прямой ссылке)
  - Есть возможность выбора уровня игры
  - Задачи даны на 2 языках (русский и английский)
  - Есть возможность просмотра игры другими пользователями
  - Есть возможность отправки сообщений друг другу зарегистрированным пользователям
  - Завершенная игра доступна в записи
  - Пользолватели получают очки, на основе которых строится рейтинг за неделю, месяц и за все время 
non-functional:
  - Сайт должен быть разработан с учетом удобства использования и оптимизирован для скорости работы
  - Сайт должен быть безопасным и защищать данные пользователя
  - Сайт должен быть удобным на мобильном устройстве
  - Сайт должен быть протестирован на совместимость с последними версиями браузеров
  - Сайт должен быть способен обрабатывать большое количество трафика (например, 1000 одновременных пользователей)
implicit:
  - Есть возможность регистрации на сайте
